### ISSUE TITLE
Notifications Do Not Work On Monterey

### ISSUE THREAD

**Issue by applekillerbyjames** [teaminkling/mac-spotify-np#68]
> Describe your problem. Please include at least **reproduction steps**, **expected output**, and environment. 

Install app. Player works but no notification prompts.

**Environment:** macOS 12 (21A5506j)

**Comment by paced** [comment]
Thank you for the report @applekillerbyjames.

I'll need some time to investigate this bug since I'm still on Big Sur. I expect the next Apple keynote is in 5 days and I can upgrade when that's generally available.

Before then: did it work before you updated to macOS 12? What version of Now Playing are you using? Have you given "Spotify" notification permissions? Should look like this:

![image](https://user-images.githubusercontent.com/15013453/132810093-1969ef71-49b4-4d5a-8310-e2c5b09ff24b.png)

**Comment by applekillerbyjames** [comment]
I am not getting the notification permission prompt.

**Comment by applekillerbyjames** [comment]
> Thank you for the report @applekillerbyjames.
> 
> 
> 
> I'll need some time to investigate this bug since I'm still on Big Sur. I expect the next Apple keynote is in 5 days and I can upgrade when that's generally available.
> 
> 
> 
> Before then: did it work before you updated to macOS 12? What version of Now Playing are you using? Have you given "Spotify" notification permissions? Should look like this:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/15013453/132810093-1969ef71-49b4-4d5a-8310-e2c5b09ff24b.png)
> 
> 

I have also not used Now Playing before Monterey.

**Comment by paced** [comment]
Okay, I am currently investigating this problem. It's either a bug in the notifier or a bug in the permissions, so either way I'll release a patch version for this when I can.

**Comment by paced** [comment]
Whoops, I set it to closed a bit too early. Version v0.9.1 is being drafted. I will link it once it's finished.

**Comment by paced** [comment]
[v0.9.1](https://github.com/teaminkling/mac-spotify-np/releases/tag/v0.9.1) has been released! Please let me know if this solves your issue.

**Comment by applekillerbyjames** [comment]
<img width="370" alt="Screen Shot 2021-09-15 at 12 57 52 PM" src="https://user-images.githubusercontent.com/43358890/133500889-3fbbaa57-73b4-4123-9def-e7bc4dad5865.png">

YESSSSS!!! thank you

**Comment by applekillerbyjames** [comment]
if I may what exactly was the issue?

**Comment by paced** [comment]
@applekillerbyjames No problem!

In short, the issue was that we were running a very old version of our notifications library `node-notifier`, `v5.3.0`. I bumped up the version to `v10.0.0` which should include support for the notifications API on beta versions of macOS.

A lot of our modernisation process from the previous maintainer was to update very old libraries and get the whole thing more secure. With `node-notifier` updated, I can say we're safely entirely in 2021 now.

**Comment by applekillerbyjames** [comment]
additionally, the play/pause shuffle doesn't work either.

**Comment by paced** [comment]
Seems to work on my machine.

Sometimes that happens on first load, if restarting both Now Playing and Spotify doesn't work, please raise another issue and I'll look into it.
